package domain

import "errors"

var (
	ErrDuplicateEmail             = errors.New("email already exists")
	ErrDuplicateUsername          = errors.New("username already exists")
	ErrInvalidEmail               = errors.New("invalid email format")
	ErrInvalidUsername            = errors.New("invalid username")
	ErrWeakPassword               = errors.New("password too weak")
	ErrUserNotFound               = errors.New("user not found")
	ErrNoFieldsToUpdate           = errors.New("no fields to update")
	ErrInvalidCredentials         = errors.New("invalid credentials")
	ErrInvalidToken               = errors.New("invalid token")
	ErrExpiredToken               = errors.New("expired token")
	ErrRefreshTokenNotFound       = errors.New("refresh token not found")
	ErrRefreshTokenRevoked        = errors.New("refresh token revoked")
	ErrRefreshTokenExpired        = errors.New("refresh token expired")
	ErrInvalidRole                = errors.New("invalid role")
	ErrInvalidID                  = errors.New("invalid id")
	ErrServerNotFound             = errors.New("server not found")
	ErrRoomNotFound               = errors.New("room not found")
	ErrMessageNotFound            = errors.New("message not found")
	ErrRoomMembershipNotFound     = errors.New("room membership not found")
	ErrForbidden                  = errors.New("forbidden")
	ErrServerRoleNotFound         = errors.New("server role not found")
	ErrServerRoleAlreadyExists    = errors.New("server role with this name already exists")
	ErrServerBanNotFound          = errors.New("server ban not found")
	ErrUserAlreadyBanned          = errors.New("user is already banned from this server")
	ErrPermissionOverrideNotFound = errors.New("permission override not found")
	ErrInvitationNotFound         = errors.New("invitation not found")
	ErrInvitationExpired          = errors.New("invitation has expired")
	ErrInvitationMaxUsesReached   = errors.New("invitation has reached its maximum uses")
	ErrAlreadyMember              = errors.New("user is already a member of this server")
	ErrDMChannelNotFound          = errors.New("dm channel not found")
	ErrDMYourself                 = errors.New("you can not dm yourself")
	ErrFriendshipNotFound         = errors.New("friendship not found")
	ErrAlreadyFriends             = errors.New("already friends or request pending")
	ErrCannotFriendYourself       = errors.New("cannot send friend request to yourself")
	ErrNotYourFriendRequest       = errors.New("not your friend request")
	ErrNotYourFriend              = errors.New("not your friend")
)
